
package projetofaculdade;

import entity.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projetofaculdade.dao.UsuarioDAO;

/**
 *
 * @author Jmariofreitas
 */
public class Cadastro extends javax.swing.JFrame {
    private final UsuarioDAO usuarioDAO;
    
       

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        setTitle("Cadastro de Usuário");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        // Inicializa o usuarioDAO
        usuarioDAO = new UsuarioDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoIdade = new javax.swing.JTextField();
        campoIEmail = new javax.swing.JTextField();
        campoIEndereco = new javax.swing.JTextField();
        buttonCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro");

        jLabel2.setText("Nome:");

        jLabel3.setText("Email");

        jLabel4.setText("Idade");

        jLabel5.setText("Endereço:");

        campoNome.setToolTipText("");

        campoIdade.setToolTipText("");

        campoIEmail.setToolTipText("");

        campoIEndereco.setToolTipText("");

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoIEndereco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoIEmail))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(buttonCadastrar)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(campoIEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(campoIEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(buttonCadastrar)
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        
    
    // Chama o método para verificar se todos os campos estão preenchidos
    if (camposEstaoPreenchidos()) {
        // Todos os campos estão preenchidos, você pode prosseguir com o cadastro
        System.out.println("Campos preenchidos:");
        System.out.println("Nome: " + campoNome.getText());
        System.out.println("Idade: " + campoIdade.getText());
        System.out.println("E-mail: " + campoIEmail.getText());
        System.out.println("Endereço: " + campoIEndereco.getText());
        System.out.println("Cadastrando usuarios no banco");
        
        if (validarFormatoEmail()) {
                cadastrarNovoUsuario();
            } else {
                System.out.println("Formato de e-mail inválido!");
            }
        
       
        // Aqui você pode prosseguir com a lógica para cadastrar os dados
    } else {
        // Caso algum campo não esteja preenchido, exibe uma mensagem
        System.out.println("Preencha todos os campos!");
    }
    }//GEN-LAST:event_buttonCadastrarActionPerformed

   
    // Método para verificar se todos os campos estão preenchidos
private boolean camposEstaoPreenchidos() {
    return !campoNome.getText().isEmpty() && !campoIdade.getText().isEmpty() && !campoIEmail.getText().isEmpty() && !campoIEndereco.getText().isEmpty();


}

// Método para validar o formato do e-mail
    private boolean validarFormatoEmail() {
        String email = campoIEmail.getText();
        String emailRegex = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$";

        if (email.matches(emailRegex)) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Formato de e-mail inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

 private void cadastrarNovoUsuario() {
        String nome = campoNome.getText();
        String idade = campoIdade.getText();
        String email = campoIEmail.getText();
        String endereco = campoIEndereco.getText();
        

        Usuario novoUsuario = new Usuario();
        novoUsuario.setNome(nome);
        novoUsuario.setIdade(idade);
        novoUsuario.setEmail(email);
        novoUsuario.setEndereco(endereco);
       

        usuarioDAO.cadastrarUsuario(novoUsuario);
        mostrarMensagemCadastroSucesso();
        limpaCampos();
    }



   public void mostrarMensagemCadastroSucesso() {
        JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");
    }

    private void limpaCampos()
    {
        campoNome.setText("");
        campoIdade.setText("");
        campoIEndereco.setText("");
        campoIEmail.setText("");
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JTextField campoIEmail;
    private javax.swing.JTextField campoIEndereco;
    private javax.swing.JTextField campoIdade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
