/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofaculdade;

import entity.Usuario;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import projetofaculdade.dao.UsuarioDAO;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Jmariofreitas
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
       public TelaInicial() {
           initComponents();
           usuarioDAO = new UsuarioDAO();
           setIcon();
           atualizarDataHora(); // Chama o método para exibir a data e hora atuais
           
           //hints dos botões
           hints();

           // Define um temporizador para atualizar a cada segundo
           javax.swing.Timer timer = new javax.swing.Timer(1000, e -> atualizarDataHora());
           timer.start();
            // Redimensione e defina a imagem para o botão
            
            configureTransparentButton(botao1, "/img/cad.png");
            configureTransparentButton(botao2, "/img/edit.png");
            configureTransparentButton(botao3, "/img/list.png");
            configureTransparentButton(botao4, "/img/excluir.png");
       

    // Cria um novo painel para organizar o conteúdo
           JPanel panel = new JPanel(new GridBagLayout());
           GridBagConstraints gbc = new GridBagConstraints();
           gbc.gridx = 0; // Define a posição x
           gbc.gridy = 0; // Define a posição y
           gbc.gridwidth = GridBagConstraints.REMAINDER; // Ocupa toda a largura
           gbc.anchor = GridBagConstraints.PAGE_START; // Alinhamento no início da tela
           gbc.insets = new Insets(20, 0, 0, 0); // Margem para a parte superior

// Adiciona o JLabel 'titulo' com as configurações de GridBagConstraints
           panel.add(titulo, gbc);

// Cria um novo painel para o campo "dataHora"
           JPanel dataHoraPanel = new JPanel();
           dataHoraPanel.setLayout(new GridBagLayout());
           GridBagConstraints dataHoraGBC = new GridBagConstraints();
           dataHoraGBC.gridx = 0; // Define a posição x
           dataHoraGBC.gridy = 0; // Define a posição y
           dataHoraGBC.gridwidth = 1; // Ocupa uma única célula
           dataHoraGBC.anchor = GridBagConstraints.LINE_END; // Alinhamento à direita

// Adiciona o JLabel 'dataHora' ao novo painel
           dataHoraPanel.add(dataHora, dataHoraGBC);

// Adiciona o novo painel de dataHora ao painel principal
           gbc.gridy = 1; // Posição abaixo do título
           gbc.anchor = GridBagConstraints.PAGE_END; // Alinhamento no início da tela
           gbc.insets = new Insets(0, 0, 0, 0); // Margem zero
           panel.add(dataHoraPanel, gbc);

// Adiciona o novo painel ao layout do conteúdo da tela
           getContentPane().setLayout(new BorderLayout());
           getContentPane().add(panel, BorderLayout.NORTH);


    
  }







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        dataHora = new javax.swing.JLabel();
        botao1 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");

        titulo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        titulo.setText("TELA DE CADASTRO");
        titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        dataHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dataHora.setText("Data/Hora");
        dataHora.setAutoscrolls(true);

        botao1.setBackground(java.awt.Color.white);
        botao1.setForeground(new java.awt.Color(252, 252, 252));
        botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cad.png"))); // NOI18N
        botao1.setText("Insert");
        botao1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botao1MouseMoved(evt);
            }
        });
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        botao2.setText("jButton1");

        botao4.setText("jButton1");

        botao3.setText("jButton1");

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Listar Cadastros");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem4.setText("Editar Usuario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem3.setText("Excluir Usuarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Extras");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 615, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(dataHora)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
              java.awt.EventQueue.invokeLater(() -> {
                Cadastro app = new Cadastro();
                app.setVisible(true);
            }); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        
        
        java.awt.EventQueue.invokeLater(() -> {
                ListarUsuarios app = new ListarUsuarios();
                app.setVisible(true);
            }); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png")));
    }
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         String idUsuario = JOptionPane.showInputDialog("Digite o ID do usuário a ser editado:");
         if (idUsuario != null && !idUsuario.isEmpty()) {
             
              int id = Integer.parseInt(idUsuario);
              Usuario usuario;
              usuario = usuarioDAO.buscarUsuario(id);
              if(usuario != null){
                  
                 
                  EditarUsuario editarUsuarioForm = new EditarUsuario();
                  editarUsuarioForm.preencherCampos(usuario);
                  editarUsuarioForm.setVisible(true); 
                  
              }else{
                  System.out.println("Nenhum usuario encontrado para esse ID");
              
              }
         
         }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        // TODO add your handling code here:
        
         Cadastro chamarTelaCadastrarUsuario = new Cadastro();
        chamarTelaCadastrarUsuario.setVisible(true);
        
        
    }//GEN-LAST:event_botao1ActionPerformed

    private void botao1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botao1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    private void atualizarDataHora() {
        LocalDateTime dataHoraAtual = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String dataHoraFormatada = dataHoraAtual.format(formatter);
        // Atualiza o texto do JLabel "dataHora"
        dataHora.setText("" + dataHoraFormatada);
    }
    
     // Método para redimensionar e definir a imagem para um botão
    private void setButtonImage(JButton button, String imagePath) {
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        Image img = icon.getImage();
        int newWidth = button.getWidth();  // Largura do botão
        int newHeight = button.getHeight();  // Altura do botão
        Image newImg = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        icon = new ImageIcon(newImg);
        button.setIcon(icon);
    }
    
     // Método para configurar um botão com imagem e torná-lo transparente
    private void configureTransparentButton(JButton button, String imagePath) {
        // Redimensiona e define a imagem para o botão
        setButtonImage(button, imagePath);
        
        // Torna o botão transparente
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
    }
    
    private void hints(){
        botao1.setToolTipText("Clique para Cadastrar");
        botao2.setToolTipText("Este é o botão 2");
        botao3.setToolTipText("Este é o botão 3");
        botao4.setToolTipText("Este é o botão 4");
    }
 
    private final UsuarioDAO usuarioDAO;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JLabel dataHora;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
